config/routes.rb
School::Application.routes.draw do

  devise_for :users

  root to: "welcome#index"
  resources :joins
  resources :hschools
  resources :mengs
  resources :abouts
  resources :contacts
  resources :dongs
  resources :meets
  resources :guans
  resources :shenqings
  resources :fellowships 
  get "success" => "mengs#success"
  get "successt" => "shenqings#success"
  get "error" => "mengs#error"
  get "errort" => "shenqings#error"
  resources :hschools do
    collection do
      match 'search' => 'hschools#search', via: [:get, :post], as: :search
    end
  end
  namespace :admin do
    root :to => 'meets#index'
    resources :contacts
    resources :joins
    resources :meets
    resources :abouts
    resources :mengs
    resources :lians
    resources :hschools
    resources :fellowships
    resources :shenqings
    resources :essays
    resources :dongs
    resources :guans
  end
end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :content
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :content
end

app/models/dong.rb
class Dong < ActiveRecord::Base
  attr_accessible :content
end

app/models/fellowship.rb
class Fellowship < ActiveRecord::Base
  attr_accessible :lei, :name, :num
  has_many :guans
  has_many :shenqings, :through => :guans
end

app/models/guan.rb
class Guan < ActiveRecord::Base
  attr_accessible :fellowship_id, :shenqing_id
  belongs_to :fellowship
  belongs_to :shenqing
end

app/models/hschool.rb
class Hschool < ActiveRecord::Base
  attr_accessible :place, :ranking, :religion, :result, :scale, :lei
end

app/models/join.rb
class Join < ActiveRecord::Base
  attr_accessible :content
end

app/models/lian.rb
class Lian < ActiveRecord::Base
  attr_accessible :addr, :name
end

app/models/meet.rb
class Meet < ActiveRecord::Base
  attr_accessible :content, :avatar
  has_attached_file :avatar
end

app/models/meng.rb
class Meng < ActiveRecord::Base
  attr_accessible :company, :email, :li, :name, :phone, :qq, :zhi
  validates_presence_of :company, :name, :email, :phone, :qq, :zhi
end

app/models/shenqing.rb
class Shenqing < ActiveRecord::Base
  attr_accessible :ability, :abilitya, :abilityb, :adept, :bir, :cert, :certa, :certb, :email, :hobby, :htime, :htimea, :htimeb, :lang, :langa, :langb, :learn, :learna, :learnb, :learnc, :name, :phone, :pro, :proa, :prob, :proc, :record, :recorda, :recordb, :recordc, :school, :schoola, :schoolb, :schoolc, :sex, :shen, :tell, :time, :timea, :timeb, :timec, :level, :jtime, :jtimea, :jtimeb, :project, :projecta, :projectb, :award, :awarda, :awardb, :remark, :remarka, :remarkb
  has_many :guans
  has_many :fellowships, :through => :guans
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/joins_controller.rb
class Admin::JoinsController < Admin::ApplicationController
  def new
    @join = Join.new
  end

  def create
    @join = Join.create(params[:join])
    redirect_to admin_joins_path
  end

  def index
    @join = Join.last
  end

  def edit
    @join = Join.find(params[:id])
  end

  def update
    @join = Join.find(params[:id])
    @join.update_attributes(params[:join])
    redirect_to admin_joins_path
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  def index
    @join = Join.last
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/joins_helper.rb
module Admin::JoinsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dongs_helper.rb
module DongsHelper
end

app/helpers/guans_helper.rb
module GuansHelper
end

app/helpers/hschools_helper.rb
module HschoolsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/mengs_helper.rb
module MengsHelper
end

app/helpers/shenqings_helper.rb
module ShenqingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/joins/edit.html.erb
<%= render "layouts/title"%>
<div class="container-fluid" style="padding-top:1%">
  <div class="row-fluid">
    <div class="span2" style="padding-top:2%">
      <!--Sidebar content-->
      <%= render "layouts/left"%>
    </div>
    <div class="span6">
      <h4>更新活动信息</h4>
      <div>
        <%= form_for [:admin, @join],:url => { :controller => '/admin/joins', :action => 'update', :id => @join },:html => { :multipart => true } do |f| %>
          <%= f.kindeditor :content%>
          <%= f.submit "更新", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/joins/index.html.erb
<%= render "layouts/title"%>
<div class="container-fluid" style="padding-top:1%">
  <div class="row-fluid">
    <div class="span2" style="padding-top:2%">
      <!--Sidebar content-->
      <%= render "layouts/left"%>
    </div>
    <div class="span6">
      <div style="padding-top:4%">
        <%=raw @join.content %>
        <p></p>
        <p>
          <%= link_to '更新', edit_admin_join_path(@join), class: "btn btn-primary"%>
        </p>
      </div>
      <!--end-->
    </div>
  </div>
</div>

app/views/admin/joins/new.html.erb
<%= render "layouts/title"%>
<div class="container-fluid" style="padding-top:1%">
  <div class="row-fluid">
    <div class="span2" style="padding-top:2%">
      <!--Sidebar content-->
      <%= render "layouts/left"%>
    </div>
    <div class="span6">
      <h4>发表加入我们信息</h4>
      <div>
        <%= simple_form_for [:admin, @join] do |m| %>
          <%= m.kindeditor :content %>
          <p></p>
          <%= m.button :submit, "保存", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>