config/routes.rb
School::Application.routes.draw do

  devise_for :users

  root to: "welcome#index"
  resources :joins
  resources :hschools
  resources :mengs
  resources :abouts
  resources :contacts
  resources :dongs
  resources :meets
  resources :guans
  resources :shenqings
  resources :fellowships 
  get "success" => "mengs#success"
  get "successt" => "shenqings#success"
  get "error" => "mengs#error"
  get "errort" => "shenqings#error"
  resources :hschools do
    collection do
      match 'search' => 'hschools#search', via: [:get, :post], as: :search
    end
  end
  namespace :admin do
    root :to => 'meets#index'
    resources :contacts
    resources :joins
    resources :meets
    resources :abouts
    resources :mengs
    resources :lians
    resources :hschools
    resources :fellowships
    resources :shenqings
    resources :essays
    resources :dongs
    resources :guans
  end
end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :content
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :content
end

app/models/dong.rb
class Dong < ActiveRecord::Base
  attr_accessible :content
end

app/models/fellowship.rb
class Fellowship < ActiveRecord::Base
  attr_accessible :lei, :name, :num
  has_many :guans
  has_many :shenqings, :through => :guans
end

app/models/guan.rb
class Guan < ActiveRecord::Base
  attr_accessible :fellowship_id, :shenqing_id
  belongs_to :fellowship
  belongs_to :shenqing
end

app/models/hschool.rb
class Hschool < ActiveRecord::Base
  attr_accessible :place, :ranking, :religion, :result, :scale, :lei
end

app/models/join.rb
class Join < ActiveRecord::Base
  attr_accessible :content
end

app/models/lian.rb
class Lian < ActiveRecord::Base
  attr_accessible :addr, :name
end

app/models/meet.rb
class Meet < ActiveRecord::Base
  attr_accessible :content, :avatar
  has_attached_file :avatar
end

app/models/meng.rb
class Meng < ActiveRecord::Base
  attr_accessible :company, :email, :li, :name, :phone, :qq, :zhi
  validates_presence_of :company, :name, :email, :phone, :qq, :zhi
end

app/models/shenqing.rb
class Shenqing < ActiveRecord::Base
  attr_accessible :ability, :abilitya, :abilityb, :adept, :bir, :cert, :certa, :certb, :email, :hobby, :htime, :htimea, :htimeb, :lang, :langa, :langb, :learn, :learna, :learnb, :learnc, :name, :phone, :pro, :proa, :prob, :proc, :record, :recorda, :recordb, :recordc, :school, :schoola, :schoolb, :schoolc, :sex, :shen, :tell, :time, :timea, :timeb, :timec, :level, :jtime, :jtimea, :jtimeb, :project, :projecta, :projectb, :award, :awarda, :awardb, :remark, :remarka, :remarkb
  has_many :guans
  has_many :fellowships, :through => :guans
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/mengs_controller.rb
class Admin::MengsController < Admin::ApplicationController
  def index
    @meng = Meng.page(params[:page]).per(30).order("id DESC")
  end

  def destroy
    @meng = Meng.find(params[:id])
    @meng.destroy
    redirect_to admin_mengs_path
  end
end

app/controllers/mengs_controller.rb
class MengsController < ApplicationController
  def new
    @meng = Meng.new
  end

  def create
    @meng = Meng.create(params[:meng])
    if @meng.save
      redirect_to success_path
    else
      redirect_to error_path
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/mengs_helper.rb
module Admin::MengsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dongs_helper.rb
module DongsHelper
end

app/helpers/guans_helper.rb
module GuansHelper
end

app/helpers/hschools_helper.rb
module HschoolsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/mengs_helper.rb
module MengsHelper
end

app/helpers/shenqings_helper.rb
module ShenqingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/mengs/index.html.erb
<%= render "layouts/title"%>
<div class="container-fluid" style="padding-top:1%">
  <div class="row-fluid">
    <div class="span2" style="padding-top:2%">
      <!--Sidebar content-->
      <%= render "layouts/left"%>
    </div>
    <div class="span6">
      <div style="padding-top:4%">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>姓名</th>
              <th>电话</th>
              <th>QQ</th>
              <th>邮箱</th>
              <th>就职公司</th>
              <th>职位</th>
              <th>加入理由</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            <% @meng.each do |m| %>
              <tr>
                <td><%= m.name %></td>
                <td><%= m.phone %></td>
                <td><%= m.qq %></td>
                <td><%= m.email %></td>
                <td><%= m.company %></td>
                <td><%= m.zhi %></td>
                <td><%= m.li %></td>
                <td>
                  <%= link_to "删除", admin_meng_path(m), :method => :delete %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!--end-->
    </div>
  </div>
</div>