config/routes.rb
School::Application.routes.draw do

  devise_for :users

  root to: "welcome#index"
  resources :joins
  resources :hschools
  resources :mengs
  resources :abouts
  resources :contacts
  resources :dongs
  resources :meets
  resources :guans
  resources :shenqings
  resources :fellowships 
  get "success" => "mengs#success"
  get "successt" => "shenqings#success"
  get "error" => "mengs#error"
  get "errort" => "shenqings#error"
  resources :hschools do
    collection do
      match 'search' => 'hschools#search', via: [:get, :post], as: :search
    end
  end
  namespace :admin do
    root :to => 'meets#index'
    resources :contacts
    resources :joins
    resources :meets
    resources :abouts
    resources :mengs
    resources :lians
    resources :hschools
    resources :fellowships
    resources :shenqings
    resources :essays
    resources :dongs
    resources :guans
  end
end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :content
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :content
end

app/models/dong.rb
class Dong < ActiveRecord::Base
  attr_accessible :content
end

app/models/fellowship.rb
class Fellowship < ActiveRecord::Base
  attr_accessible :lei, :name, :num
  has_many :guans
  has_many :shenqings, :through => :guans
end

app/models/guan.rb
class Guan < ActiveRecord::Base
  attr_accessible :fellowship_id, :shenqing_id
  belongs_to :fellowship
  belongs_to :shenqing
end

app/models/hschool.rb
class Hschool < ActiveRecord::Base
  attr_accessible :place, :ranking, :religion, :result, :scale, :lei
end

app/models/join.rb
class Join < ActiveRecord::Base
  attr_accessible :content
end

app/models/lian.rb
class Lian < ActiveRecord::Base
  attr_accessible :addr, :name
end

app/models/meet.rb
class Meet < ActiveRecord::Base
  attr_accessible :content, :avatar
  has_attached_file :avatar
end

app/models/meng.rb
class Meng < ActiveRecord::Base
  attr_accessible :company, :email, :li, :name, :phone, :qq, :zhi
  validates_presence_of :company, :name, :email, :phone, :qq, :zhi
end

app/models/shenqing.rb
class Shenqing < ActiveRecord::Base
  attr_accessible :ability, :abilitya, :abilityb, :adept, :bir, :cert, :certa, :certb, :email, :hobby, :htime, :htimea, :htimeb, :lang, :langa, :langb, :learn, :learna, :learnb, :learnc, :name, :phone, :pro, :proa, :prob, :proc, :record, :recorda, :recordb, :recordc, :school, :schoola, :schoolb, :schoolc, :sex, :shen, :tell, :time, :timea, :timeb, :timec, :level, :jtime, :jtimea, :jtimeb, :project, :projecta, :projectb, :award, :awarda, :awardb, :remark, :remarka, :remarkb
  has_many :guans
  has_many :fellowships, :through => :guans
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/meets_controller.rb
class Admin::MeetsController < Admin::ApplicationController
  def new
    @meet = Meet.new
  end

  def create
    @meet = Meet.create(params[:meet])
    redirect_to admin_meets_path
  end

  def index
    @meet = Meet.all
  end

  def edit
    @meet = Meet.find(params[:id])
  end

  def update
    @meet = Meet.find(params[:id])
    @meet.update_attributes(params[:meet])
    redirect_to admin_meets_path
  end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  def index
    @meet = Meet.last
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/meets_helper.rb
module Admin::MeetsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dongs_helper.rb
module DongsHelper
end

app/helpers/guans_helper.rb
module GuansHelper
end

app/helpers/hschools_helper.rb
module HschoolsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/mengs_helper.rb
module MengsHelper
end

app/helpers/shenqings_helper.rb
module ShenqingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/meets/index.html.erb
<div id="wrapper" class="clearfix">
  
  <div id="header">
    
    <div class="container">
      
      <h1 id="title">
        <%= link_to "Focus Business", root_path%>
      </h1>
      
    </div> <!-- /container -->
    
  </div> <!-- /header --> 
  
  
  <div id="nav" class="clearfix">
    
    <div class="container">
    
      <ul id="main-nav">
        <li class="active">
          <%= link_to "最新活动", dongs_path%>
        <li>
          <%= link_to "奖学金申请", fellowships_path%>
        </li>
        
        <li>
          <%= link_to "美国高中联盟", hschools_path%>
        </li>
        
        <li>
          <%= link_to "家长联盟", new_meng_path%>
        </li>       
        
      </ul>
      
    </div> <!-- /container -->
    
  </div> <!-- /nav -->
  
  
  <div id="page-title">
    
    <h1>最新活动</h1>
  </div> <!-- /page-title -->
  <div id="content">
    
    <div class="container">
      
      <div class="row">
        
        <div class="grid-12">
          
          <div class="pricing-plans plans-4">
            
            <div class="plan-container">
              <%= @meet.content%>              
            </div> <!-- /plan-container -->
              
          </div> <!-- /pricing-plans -->
          
        </div> <!-- /grid-12 -->
        
      </div> <!-- /row -->
      
    </div> <!-- /container -->
    
  </div> <!-- /content -->
  
  
  
  <div id="footer">
    <%= render "layouts/footer"%>    
  </div> <!-- /footer -->
  
  
  
  <div id="copyright">
    
    <div class="container">
      
      <div class="row">
      
        <div id="rights" class="grid-6">
        © 2013 Propel UI. All Rights Reserved.
        </div> <!-- /grid-6 -->
        
        <div id="totop" class="grid-2">
          <%= link_to "关于我们", abouts_path %>
        </div> <!-- /grid-6 -->
        <div id="totop" class="grid-2">
          <%= link_to "联系我们", contacts_path %>
        </div> <!-- /grid-6 -->
        <div id="totop" class="grid-2">
          <%= link_to "加入我们", joins_path %>
        </div> <!-- /grid-6 -->
        
      </div> <!-- /row -->
      
    </div> <!-- /container -->
      
  </div> <!-- /copyright -->
  
</div> <!-- /wrapper -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="./js/jquery-1.7.2.min.js"></script>

<script src="./js/bootstrap.min.js"></script>
<script src="./js/focus.js"></script>

<script>

$(function () {
  
  
});

</script>